FROM node:12.17.0

ARG AUTH0_DOMAIN
ARG AUTH0_CLIENT_ID
ARG AUTH0_CLIENT_SECRET
ARG REDIRECT_URI
ARG POST_LOGOUT_REDIRECT_URI
ARG SESSION_COOKIE_SECRET

ARG PGHOST
ARG PGUSER
ARG PGPASSWORD
ARG PGDATABASE
ARG PGSSLMODE
ARG SSH_DATABASE_CERTIFICATE

ENV AUTH0_DOMAIN $AUTH0_DOMAIN
ENV AUTH0_CLIENT_ID $AUTH0_CLIENT_ID
ENV AUTH0_CLIENT_SECRET $AUTH0_CLIENT_SECRET
ENV REDIRECT_URI $REDIRECT_URI
ENV POST_LOGOUT_REDIRECT_URI $POST_LOGOUT_REDIRECT_URI
ENV SESSION_COOKIE_SECRET $SESSION_COOKIE_SECRET

ENV PGHOST $PGHOST
ENV PGUSER $PGUSER
ENV PGPASSWORD $PGPASSWORD
ENV PGDATABASE $PGDATABASE
ENV PGSSLMODE $PGSSLMODE
ENV SSH_DATABASE_CERTIFICATE $SSH_DATABASE_CERTIFICATE


WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn cache clean && yarn --update-checksums
COPY . ./
RUN yarn && yarn build
CMD [ "yarn", "start" ]


