FROM node:12.17.0

## Receiving arguments 

ARG AUTH0_DOMAIN
ARG AUTH0_CLIENT_ID
ARG AUTH0_CLIENT_SECRET
ARG REDIRECT_URI
ARG POST_LOGOUT_REDIRECT_URI
ARG SESSION_COOKIE_SECRET

ARG PGHOST
ARG PGUSER
ARG PGPORT
ARG PGPASSWORD
ARG PGDATABASE
ARG PGSSLMODE
ARG SSH_DATABASE_CERTIFICATE

# -- location on server 
ARG HTTPS_SERVER_PRIVKEY
ARG HTTPS_SERVER_FULLCHAIN
ARG HTTPS_SERVER_CHAIN

# -- copied to this location in container
ARG HTTPS_CONTAINER_PRIVKEY
ARG HTTPS_CONTAINER_FULLCHAIN
ARG HTTPS_CONTAINER_CHAIN


## Assigning arguments to environment variables: 

ENV AUTH0_DOMAIN $AUTH0_DOMAIN
ENV AUTH0_CLIENT_ID $AUTH0_CLIENT_ID
ENV AUTH0_CLIENT_SECRET $AUTH0_CLIENT_SECRET
ENV REDIRECT_URI $REDIRECT_URI
ENV POST_LOGOUT_REDIRECT_URI $POST_LOGOUT_REDIRECT_URI
ENV SESSION_COOKIE_SECRET $SESSION_COOKIE_SECRET

ENV PGHOST $PGHOST
ENV PGUSER $PGUSER
ENV PGPORT $PGPORT
ENV PGPASSWORD $PGPASSWORD
ENV PGDATABASE $PGDATABASE
ENV PGSSLMODE $PGSSLMODE
ENV SSH_DATABASE_CERTIFICATE $SSH_DATABASE_CERTIFICATE

ENV HTTPS_CONTAINER_PRIVKEY $HTTPS_CONTAINER_PRIVKEY
ENV HTTPS_CONTAINER_FULLCHAIN $HTTPS_CONTAINER_FULLCHAIN
ENV HTTPS_CONTAINER_CHAIN $HTTPS_CONTAINER_CHAIN


WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn cache clean && yarn --update-checksums
COPY . ./

COPY ${HTTPS_SERVER_PRIVKEY} ${HTTPS_CONTAINER_PRIVKEY}
COPY ${HTTPS_SERVER_FULLCHAIN} ${HTTPS_CONTAINER_FULLCHAIN}
COPY ${HTTPS_SERVER_CHAIN} ${HTTPS_CONTAINER_CHAIN}
RUN yarn && yarn build
CMD [ "yarn", "start" ]


