version: '3'
services:
  web:
    #image: cypress/base:14.15.0 # Node + Cypress 
    image: cypress/browsers:node12.14.1-chrome85-ff81
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

    links:
      - db
  
  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data