name: Email Summary Cron

on:
  schedule:
  - cron: '30 07 1,15 * *' # 1 and 15 every month, at 07:30

jobs:
  triggers:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - run: curl "https://krets.app/api/summary-email-trigger?secret=${{secrets.SUMMARY_EMAIL_SECRET}}" #krets.app/api/summary-email-trigger