name: Running Integration Tests

on: [push, pull_request]

jobs:
  integration-tests:

    runs-on: ubuntu-latest
    services:
      localhost:
        image: postgres
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: user
          POSTGRES_DB: data
        options: 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v2.2.7
      with: 
        command: yarn test:integration
      env:
        PGHOST: localhost
        PGUSER: user
        PGPASSWORD: pass
        PGDATABASE: data
