name: Report usage to Stripe

#TODO: implement 
#TODO: double check cron 
on:
    schedule: 
        - cron: '0 12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # replace with http call 
    
